DROP PROCEDURE IF EXISTS `delete_all_data`;

DELIMITER //

CREATE PROCEDURE `delete_all_data` ()

BEGIN
	SET `SQL_SAFE_UPDATES` = 0;

    -- TB_REGISTRO_EXAME
	DELETE FROM `TB_REGISTRO_EXAME`;
    ALTER TABLE `TB_REGISTRO_EXAME` AUTO_INCREMENT = 1;

    -- TB_MEDICO_ESPECIALIDADE
	DELETE FROM `TB_MEDICO_ESPECIALIDADE`;
    ALTER TABLE `TB_MEDICO_ESPECIALIDADE` AUTO_INCREMENT = 1;

    -- TB_ESPECIALIDADE
	DELETE FROM `TB_ESPECIALIDADE`;
    ALTER TABLE `TB_ESPECIALIDADE` AUTO_INCREMENT = 1;

    -- TB_MEDICO
	DELETE FROM `TB_MEDICO`;
    ALTER TABLE `TB_MEDICO` AUTO_INCREMENT = 1;

    -- TB_DEBITO
	DELETE FROM `TB_DEBITO`;
    ALTER TABLE `TB_DEBITO` AUTO_INCREMENT = 1;

    -- TB_TIPO_DEBITO
	DELETE FROM `TB_TIPO_DEBITO`;
    ALTER TABLE `TB_TIPO_DEBITO` AUTO_INCREMENT = 1;

    -- TB_EXAME
	DELETE FROM `TB_EXAME`;
    ALTER TABLE `TB_EXAME` AUTO_INCREMENT = 1;

    -- TB_PACIENTE
	DELETE FROM `TB_PACIENTE`;
    ALTER TABLE `TB_PACIENTE` AUTO_INCREMENT = 1;

    -- TB_CONVENIO
	DELETE FROM `TB_CONVENIO`;
    ALTER TABLE `TB_CONVENIO` AUTO_INCREMENT = 1;

    SET `SQL_SAFE_UPDATES` = 1;
END//

DELIMITER ;