-- MySQL Script generated by MySQL Workbench
-- Mon May  2 22:04:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_laboratorial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica_laboratorial` ;

-- -----------------------------------------------------
-- Schema clinica_laboratorial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_laboratorial` DEFAULT CHARACTER SET utf8 ;
USE `clinica_laboratorial` ;

-- -----------------------------------------------------
-- Table `TB_PACIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_PACIENTE` ;

CREATE TABLE IF NOT EXISTS `TB_PACIENTE` (
  `id_paciente` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'DEFAULT' NOT NULL,
  `dt_nascimento` DATE NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `TB_PACIENTE` (`cpf` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TB_CONVENIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_CONVENIO` ;

CREATE TABLE IF NOT EXISTS `TB_CONVENIO` (
  `id_convenio` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `taxa_coparticipacao` DECIMAL(4,3) NOT NULL,
  PRIMARY KEY (`id_convenio`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cnpj_UNIQUE` ON `TB_CONVENIO` (`cnpj` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TB_EXAME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_EXAME` ;

CREATE TABLE IF NOT EXISTS `TB_EXAME` (
  `id_exame` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(1000) NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_exame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_MEDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_MEDICO` ;

CREATE TABLE IF NOT EXISTS `TB_MEDICO` (
  `id_medico` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `crm` VARCHAR(9) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_medico`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `crm_UNIQUE` ON `TB_MEDICO` (`crm` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TB_REGISTRO_EXAME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_REGISTRO_EXAME` ;

CREATE TABLE IF NOT EXISTS `TB_REGISTRO_EXAME` (
  `id_registro` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_exame` INT NOT NULL,
  `id_medico` INT NOT NULL,
  `id_convenio` INT NOT NULL,
  `dthora_realizacao` DATETIME NOT NULL,
  PRIMARY KEY (`id_registro`),
  CONSTRAINT `id_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `TB_PACIENTE` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_exame`
    FOREIGN KEY (`id_exame`)
    REFERENCES `TB_EXAME` (`id_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_convenio`
    FOREIGN KEY (`id_convenio`)
    REFERENCES `TB_CONVENIO` (`id_convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_medico`
    FOREIGN KEY (`id_medico`)
    REFERENCES `TB_MEDICO` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_paciente_idx` ON `TB_REGISTRO_EXAME` (`id_paciente` ASC) VISIBLE;

CREATE INDEX `id_exame_idx` ON `TB_REGISTRO_EXAME` (`id_exame` ASC) VISIBLE;

CREATE INDEX `id_convenio_idx` ON `TB_REGISTRO_EXAME` (`id_convenio` ASC) VISIBLE;

CREATE INDEX `id_medico_idx` ON `TB_REGISTRO_EXAME` (`id_medico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TB_ESPECIALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_ESPECIALIDADE` ;

CREATE TABLE IF NOT EXISTS `TB_ESPECIALIDADE` (
  `id_especialidade` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_MEDICO_ESPECIALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_MEDICO_ESPECIALIDADE` ;

CREATE TABLE IF NOT EXISTS `TB_MEDICO_ESPECIALIDADE` (
  `id` INT NOT NULL,
  `id_medico` INT NOT NULL,
  `id_especialidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_medico`
    FOREIGN KEY (`id_medico`)
    REFERENCES `TB_MEDICO` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_especialidade`
    FOREIGN KEY (`id_especialidade`)
    REFERENCES `TB_ESPECIALIDADE` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_medico_idx` ON `TB_MEDICO_ESPECIALIDADE` (`id_medico` ASC) VISIBLE;

CREATE INDEX `id_especialidade_idx` ON `TB_MEDICO_ESPECIALIDADE` (`id_especialidade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TB_TIPO_DEBITO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_TIPO_DEBITO` ;

CREATE TABLE IF NOT EXISTS `TB_TIPO_DEBITO` (
  `id_tipo` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_DEBITO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_DEBITO` ;

CREATE TABLE IF NOT EXISTS `TB_DEBITO` (
  `id_debito` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  `id_registro` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `dthora_registro` DATETIME NOT NULL,
  `dthora_pagamento` DATETIME NOT NULL,
  PRIMARY KEY (`id_debito`),
  CONSTRAINT `id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `TB_TIPO_DEBITO` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_registro`
    FOREIGN KEY (`id_registro`)
    REFERENCES `TB_REGISTRO_EXAME` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_tipo_idx` ON `TB_DEBITO` (`id_tipo` ASC) VISIBLE;

CREATE INDEX `id_registro_idx` ON `TB_DEBITO` (`id_registro` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
