-- Projeto Final: Clínica Laboratorial
-- Script de Criação
-- Criado em: 02/05/2022

DROP SCHEMA IF EXISTS `clinica_laboratorial`;

CREATE SCHEMA IF NOT EXISTS `clinica_laboratorial` DEFAULT CHARACTER SET utf8mb4;

USE `clinica_laboratorial`;

-- TB_PACIENTE
DROP TABLE IF EXISTS `TB_PACIENTE`;

CREATE TABLE IF NOT EXISTS `TB_PACIENTE` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `dt_nascimento` DATE NULL,
  PRIMARY KEY (`id_paciente`),
  UNIQUE KEY `cpf_UNIQUE` (`cpf`));

-- TB_CONVENIO
DROP TABLE IF EXISTS `TB_CONVENIO`;

CREATE TABLE IF NOT EXISTS `TB_CONVENIO` (
  `id_convenio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `taxa_coparticipacao` DECIMAL(4,3) NOT NULL,
  PRIMARY KEY (`id_convenio`),
  UNIQUE KEY `cnpj_UNIQUE` (`cnpj`));

-- TB_EXAME
DROP TABLE IF EXISTS `TB_EXAME`;

CREATE TABLE IF NOT EXISTS `TB_EXAME` (
  `id_exame` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(1000) NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_exame`));

-- TB_MEDICO
DROP TABLE IF EXISTS `TB_MEDICO`;

CREATE TABLE IF NOT EXISTS `TB_MEDICO` (
  `id_medico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `crm` VARCHAR(9) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_medico`),
  UNIQUE KEY `crm_UNIQUE` (`crm`));

-- TB_REGISTRO_EXAME
DROP TABLE IF EXISTS `TB_REGISTRO_EXAME`;

CREATE TABLE IF NOT EXISTS `TB_REGISTRO_EXAME` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `id_paciente` INT NOT NULL,
  `id_exame` INT NOT NULL,
  `id_medico` INT NOT NULL,
  `id_convenio` INT NOT NULL,
  `dthora_realizacao` DATETIME NOT NULL,
  PRIMARY KEY (`id_registro`));

-- TB_ESPECIALIDADE
DROP TABLE IF EXISTS `TB_ESPECIALIDADE`;

CREATE TABLE IF NOT EXISTS `TB_ESPECIALIDADE` (
  `id_especialidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_especialidade`));

-- TB_MEDICO_ESPECIALIDADE
DROP TABLE IF EXISTS `TB_MEDICO_ESPECIALIDADE`;

CREATE TABLE IF NOT EXISTS `TB_MEDICO_ESPECIALIDADE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_medico` INT NOT NULL,
  `id_especialidade` INT NOT NULL,
  PRIMARY KEY (`id`));

-- TB_TIPO_DEBITO
DROP TABLE IF EXISTS `TB_TIPO_DEBITO`;

CREATE TABLE IF NOT EXISTS `TB_TIPO_DEBITO` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo`));

-- TB_DEBITO
DROP TABLE IF EXISTS `TB_DEBITO`;

CREATE TABLE IF NOT EXISTS `TB_DEBITO` (
  `id_debito` INT NOT NULL AUTO_INCREMENT,
  `id_tipo` INT NOT NULL,
  `id_registro` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `dthora_registro` DATETIME NOT NULL,
  `dthora_pagamento` DATETIME NOT NULL,
  PRIMARY KEY (`id_debito`));

-- FOREIGN KEYS
-- TB_REGISTRO_EXAME
ALTER TABLE `TB_REGISTRO_EXAME` ADD FOREIGN KEY `id_paciente_fk` (`id_paciente`) REFERENCES `TB_PACIENTE` (`id_paciente`);

ALTER TABLE `TB_REGISTRO_EXAME` ADD FOREIGN KEY `id_exame_fk` (`id_exame`) REFERENCES `TB_EXAME` (`id_exame`);

ALTER TABLE `TB_REGISTRO_EXAME` ADD FOREIGN KEY `id_convenio_fk` (`id_convenio`) REFERENCES `TB_CONVENIO` (`id_convenio`);

ALTER TABLE `TB_REGISTRO_EXAME` ADD FOREIGN KEY `id_medico_fk` (`id_medico`) REFERENCES `TB_MEDICO` (`id_medico`);

-- TB_MEDICO_ESPECIALIDADE
ALTER TABLE `TB_MEDICO_ESPECIALIDADE` ADD FOREIGN KEY `id_medico_fk` (`id_medico`) REFERENCES `TB_MEDICO` (`id_medico`);

ALTER TABLE `TB_MEDICO_ESPECIALIDADE` ADD FOREIGN KEY `id_especialidade_fk` (`id_especialidade`) REFERENCES `TB_ESPECIALIDADE` (`id_especialidade`);

-- TB_DEBITO
ALTER TABLE `TB_DEBITO` ADD FOREIGN KEY `id_tipo_fk` (`id_tipo`) REFERENCES `TB_TIPO_DEBITO` (`id_tipo`);

ALTER TABLE `TB_DEBITO` ADD FOREIGN KEY `id_registro_idx` (`id_registro`) REFERENCES `TB_REGISTRO_EXAME` (`id_registro`);